#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2004-2012 University of Utah and the Flux Group.
# All rights reserved.
#

version=2.0
srcurl="http://www.postel.org/tg"
tarball="tg${version}.tar.gz"

if [ -x /usr/bin/fetch ]; then
    fetch=/usr/bin/fetch
elif [ -x /usr/bin/wget ]; then
    fetch=/usr/bin/wget
else
    echo "ERROR: tg-install: need either 'fetch' or 'wget' installed"
    exit 1
fi

if [ -n "$1" ]; then srcdir=$1; else srcdir=$PWD ; fi
if [ -n "$2" ]; then tarball=$2; fi
if [ -n "$3" ]; then host=$3; else host=www.emulab.net ; fi
dir=$PWD

if [ ! -d $dir/tg${version}/src ]; then
    if [ ! -f "$tarball" ]; then
      cd $dir
      echo "Downloading tg source from $host to $dir ..."
      $fetch http://$host/$tarball
      if [ $? -ne 0 ]; then
           echo "Failed..."
           echo "Downloading tg source from \"$srcurl\" to $dir ..."
           $fetch "$srcurl/$tarball" || {
	       echo "ERROR: tg-install: $fetch failed"
	       exit 1
	   }
      fi
    fi
    echo "Unpacking/patching tg${version} source ..."
    tar xzof $tarball || {
        echo "ERROR: tg-install: tar failed"
	exit 1
    }
    # XXX hack to deal with relative paths...argh!
    case $srcdir in
    /*)
	;;
    *)
        srcdir="../$srcdir"
	;;
    esac
    patch -p0 < $srcdir/tg.patch || {
        echo "ERROR: tg-install: patch failed"
	exit 1
    }
    rm -f tg${version}/*/*/*.orig
fi
exit 0
