#! /bin/bash
#
# Copyright (c) 2013 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

mywhich() {
    mypath=$(env | grep PATH)
    mypath=${mypath/PATH=/}
    mypath=${mypath//:/ }
    for i in $mypath ; do
	if [ -e $i/$1 ] ; then
	    echo $i/$1
	    return 0
	fi
    done
    return 1
}

if [ -z "$BINDIR" ] ; then
    if [ -r /etc/emulab/paths.sh ] ; then
	source /etc/emulab/paths.sh
    else
	BINDIR=/usr/local/etc/emulab
	LOGDIR=/var/tmp
    fi
fi
PROJDIR=/proj/emulab-ops

# need to make sure we are running with a full verseion of bash
if [ -f '/etc/emulab/ismfs' ] ; then
    # check to see if we are using correct bash
    verbash=$(file `mywhich bash`)
    if [ -z "$verbash" ] ; then
	verbash=$(file -m $PROJDIR/nodecheck/FreeBSD/bin/magic `mywhich bash`)
    fi
    if [ "$verbash" != "${verbash/busybox}" ] ; then
	# NO! we are not, retstart using the correct bash
	# we not be in a loop since correct path is now set
	export PATH=$PROJDIR/nodecheck/$(uname -s)/bin:$PATH
	bash $0
	exit 0
    fi
fi

source checkutils.sh

gatherinv_main() {
    echo -n '  Gathering Inventory..'

    $(cp /dev/null /tmp/nodecheck.log.tb)

    checks="disk cpu mem nic"
    for i in $checks ; do
	bash $BINDIR/${i}check $LOGDIR/nodecheck.log /tmp/nodecheck.log.tb
    done
set +e

    # read in the newly found info
    readtmcinfo /tmp/nodecheck.log.tb

    # print it back out for the database
    { printtmcinfo
} > /tmp/nodecheck.log.tb.new # .new not necessary should reuse name

    # print full locally found 
    { printhwinv
} > /tmp/nodecheck.log.inv

    host=$($BINDIR/tmcc nodeid)
    # make sure proj got mounted
    if [ ! -d $PROJDIR ] ; then
	echo "OHhh all this work for nothing"
	echo "$PROJDIR not mounted can't save info"
	exit 1
    fi
    # have needed dirs ?
    if [ ! -d $PROJDIR/nodecheck/FullInventory ] ; then
	mkdir -p $PROJDIR/nodecheck/FullInventory
	chmod 755 $PROJDIR/nodecheck $PROJDIR/nodecheck/FullInventory
    fi

	
    $(cp /tmp/nodecheck.log.tb.new $PROJDIR/nodecheck/$host);
    $(cp /tmp/nodecheck.log.inv $PROJDIR/nodecheck/FullInventory/$host);
    $(chmod g+rw $PROJDIR/nodecheck/$host $PROJDIR/nodecheck/FullInventory/$host);

    # Test what found local against what is in the database
    readtmcinfo # info from tmcc hwinv
# for testing    readtmcinfo $PROJDIR/nodecheck/test
    copytmcinfo # copy into hwinvcopy
    readtmcinfo /tmp/nodecheck.log.tb.new # read local found into hwinv
    comparetmcinfo /tmp/nodecheck.diff # file for output

    if [ -s /tmp/nodecheck.diff ] ; then
	cat /tmp/nodecheck.diff
	$(cp /tmp/nodecheck.diff $PROJDIR/nodecheck/${host}.diff)
	$(chmod g+rw $PROJDIR/nodecheck/${host}.diff);
    else
	# no diff maybe it got better
	rm -f $PROJDIR/nodecheck/${host}.diff
    fi
	
#    echo "NEED TO ENABLE rm -f /tmp/nodecheck.log.tb /tmp/nodecheck.log.inv"
#    echo "NEED TO ENABLE rm -f /tmp/nodecheck.log.tb.new /tmp/nodecheck.diff"
}

gatherinv_main $0





