#!/bin/bash
#
# Copyright (c) 2013 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

_1KiB=1
_1KMiB=1024
_256KMiB=262144
_1KGiB=1048576
_32KGiB=33554432

echo -n ' Starting memcheck..'

source checkutils.sh
#source getfromtb.sh
source hbis.sh

declare failed="" s=""

inithostname

## # setup logging
##if [ $1 ] ; then
##    logfile=$1
## else
##    logfile="/tmp/nodecheck.log"
## fi
## tmplog=/tmp/.$$.log
## cat /dev/null > ${tmplog}

initlogs

#set +x
#exit on unbound var
set -u

finish() {
    echo "memcheck `date`" >> ${logfile}
    cat ${tmplog} >> ${logfile} 
    
#    if [ -z "${failed}" ]
#    then
#	echo -n ""
#	echo "OK"
#    else
	echo "$failed"
	echo "$failed" >> ${logfile} 
	exit 1
#    fi
    
    exit 0
}

s=""
# check that external need program are installed
case $os in
    Linux )
	if [ -f ${logfile4tb} ] ; then
	    progs="cat grep"
	else
	    progs="cat grep bc"
	fi
	;;
    FreeBSD )
	progs="grep cat"
	;;
    * )
	failed="Unknown OS :$os:"
	finish
	exit 1
	;;
esac
for i in $progs ; do
    type $i &>/dev/null && continue  || s="$s $i "
done
if [ -n "$s" ] ; then
    failed=" Unable to run need missing command(s) $s"
    echo "$failed" >> ${tmplog}
    finish
fi


{
case $os in
    Linux )
	    unset -v d ; declare -a d=($(cat /proc/meminfo | grep MemTotal))
	    # Linux under reports, add 11MiB (in KiB units) for reserved mem
	    if [ -f ${logfile4tb} ] ; then
		meminfo=${d[1]}
		meminfo=$(($meminfo / 1000))
	    else
	    if (( ${d[1]} > $_32KGiB )) ; then
		number=$(echo "scale=0; (${d[1]} * 1.015) / 1;" | bc)
	    elif (( ${d[1]} > $_1KGiB )) ; then
		number=$(echo "scale=0; (${d[1]} * 1.03) / 1;" | bc)
	    elif (( ${d[1]} > $_256KMiB )) ; then
		number=$(echo "scale=0; (${d[1]} * 1.183) / 1;" | bc)
	    elif (( ${d[1]} > $_1KMiB )) ; then
		number=$(echo "scale=0; (${d[1]} * 1.047) / 1;" | bc)
	    else 
		number=$(echo "scale=0; (${d[1]} * 1.0) / 1;" | bc)
	    fi
	    mi=${number}${d[2]}
#echo  "$0:${LINENO} ========== was:${d[1]} now number:$number sent:$mi "
	    meminfo=$(hbis $mi)
#echo  "$0:${LINENO} ========== returned:$meminfo"
	    fi
	    ;;
    FreeBSD )
	    unset -v d ; declare -a d=($(grep memory /var/run/dmesg.boot | grep real))
	    w=${d[4]} ; x=${w#(}
		z=${d[5]} ; y=${z%)}
	    meminfo=$x$y
	    meminfo=$(hbis $meminfo)
	    ;;
    * )
	    echo "os $os unknown"
	    meminfo="0"
	    failed=FAIL
	    ;;
esac

echo -n "Found phys memory $meminfo"
} >> ${tmplog} 2>&1

# if saving data for testbed database
num=${meminfo//[a-z]*/}
num=${meminfo//[A-Z]*/}
base=${meminfo//[0-9]/}
#it is MiB or GiB
if [ "$base" == "GiB" ] ; then
    num=$(($num * 1024))
fi
if [ -f ${logfile4tb} ] ; then
    printf "MEMINFO SIZE=%s\n" ${num} >> ${logfile4tb}
    exit 0
fi

tbinfo=$(getfromtb meminfo $host)

{
if [ "$meminfo" == "$tbinfo" ] ; then
    echo " Equals node inventory $tbinfo"
else
    echo " Does not equals node inventory $tbinfo"    
    failed=FAIL
fi
} >> ${tmplog} 2>&1

echo "memcheck `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

[[ -z ${failed} ]] && echo "$tbinfo OK" || echo "TBmiss Have |$meminfo| Want |$tbinfo| FAILED"

exit 0
