#!/bin/bash
#
# Copyright (c) 2013 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

echo -n ' Starting timecheck.. '

ntpserver="ntp1"
maxdrift="0.001"

#ntpserver="time.xmission.com"

os=`uname`
host=`hostname`
failed=""
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi


# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

# check that external need program are installed
s=""
case $os in
    Linux | FreeBSD )
	progs="tr bc ntpdate"
	;;
    * )
	failed="Unknown OS :$os: FAILED"
	echo "$failed" >> ${logfile}
	echo "$failed"
	exit 1
	;;
esac
for i in $progs ; do
    type $i &>/dev/null && continue  || s="$s $i "
done
if [ -n "$s" ] ; then
    failed=" Unable to run need missing command(s) $s FAILED"
    echo "$failed" >> ${logfile}
    echo "$failed"
    exit 1
fi

#exit on unbound var
set -u

{
unset -v d ; declare -a d=()
case $os in
    Linux | FreeBSD )
	d=($(ntpdate -q $ntpserver))
	(( $? )) && failed="No Response from ntpserver:$ntpserver"

	for ((idx=0; idx<${#d[*]}; idx++)) ; do
	    [[ "${d[$idx]}" == "offset" ]] && break
	done
	((++idx))
	z=${d[$idx]}
	offset=$(echo ${z} | tr -d ,) # remove comma
	[[ $offset < 0 ]] && a=$(echo "-($offset)" | bc) || a=$(echo "($offset)") # make $a abs()
	[[ $a > $maxdrift ]] && failed="maxdrift"
	if  [ -z "${failed}" ]; then
	    echo "Time check passed offset $offset allowed $maxdrift"
	elif [ "${failed}" == "maxdrift" ] ; then
	    echo "Time check failed offset $offset greater then $maxdrift second "
	else
	    echo "${failed}"
	fi
	;;
    * )
	echo "os $os unknown"
	offset="-1"
	failed="os $os unknown"
	;;
esac
} >> ${tmplog} 2>&1

echo "timecheck `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

if [ -z "${failed}" ] ; then 
    echo "offset $offset < $maxdrift OK" 
elif [ "${failed}" == "maxdrift" ] ; then
    echo "offset $offset > $maxdrift FAILED"
else
    echo "${failed} FAILED"
fi

exit 0
