#!/bin/sh

#
# A little script to put the testbed ports into the ports tree
#

PORTSDIR=${PORTSDIR:-/usr/ports}
PORTSUBDIR=misc
SRCDIR=`dirname $0`
PORTS="emulab-abac emulab-boss emulab-fs emulab-ops emulab-tipserv emulab-tftp-hpa emulab-py-m2crypto emulab-pubsub emulab-extras emulab-protogeni p5-IO-EventMux p5-IO-EventMux-Socket-MsgHdr p5-Privileges-Drop p5-RPC-Async libtelnet otcl ipmitool-devel xerces-c2"

echo "Copying ports ..."
for PORT in $PORTS
do
    cp -r $SRCDIR/$PORT $PORTSDIR/$PORTSUBDIR
    if [ "$?" != "0" ]
    then
	exit 1
    fi
done

# "register" the emulab ports
echo "Patching $PORTSDIR/$PORTSUBDIR/Makefile ..."
patch -p0 $PORTSDIR/$PORTSUBDIR/Makefile ports.patch

echo "Done!"
exit 0
