#!/bin/sh

#
# Arrange for "prepare" to be run on the way down, and then shutdown.
#
. /etc/emulab/paths.sh

echo "$ETCDIR/prepare.sh" > /bootcmd

reboot=1
if [ $# -eq 1 ]; then
    if [ "$1" = "-noreboot" ]; then
	reboot=0
    fi
fi
if [ $reboot -eq 1 ]; then
    shutdown now "Rebooting with Prepare"
fi

exit 0
