#! /bin/sh


os=`uname`
host=`hostname`
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi

# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

set +x
#exit on unbound var
#set -u

echo "cpucheck `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

if [ -n ${failed} ]
then
    echo ". . . cpucheck OK"
else
    echo ". . . cpucheck FAILED"
fi
echo -n ""

exit 0
