#! /bin/sh


# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

set +x
#exit on unbound var
#set -u

echo "cputest `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

if [ -n ${failed} ]
then
    echo ". . . cputest OK"
else
    echo ". . . cputest FAILED"
fi
echo -n ""

exit 0
