#! /bin/bash

echo -n ' Starting diskcheck..'

# find the number of disks
# find the size of each disk

# first arg is the log output file, if not set then /tmp/...

source getfromtb.sh
source hbis.sh

SMARTCTL=""
failed=""
error=""

os=`uname -s`
host=`hostname`
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi

# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

#exit on unbound var
set -u

#need to make sure smartcrl is installed - not by default on our linux images
{
    SMARTCTL=$(which smartctl)
    if [ -z "${SMARTCTL}" ] ; then
	if [ -x "/usr/sbin/smartctl" ]; then
	    SMARTCTL="/usr/sbin/smartctl"
	fi
    fi
    if [ -x "${SMARTCTL}" ] ; then
	# unrecongnized
	rtn=$($SMARTCTL --scan | grep UNRECOGNIZED)
	[[ $rtn ]] && error="(smartctl option '--scan' not supported" && failed=scan
	# output unexpected
	rtn=$($SMARTCTL --scan | grep device)
	[[ ! $rtn ]] && error="(smartctl option '--scan' strange ouput" && failed=scan
	# empty
	rtn=$($SMARTCTL --scan)
	if [ -z "$rtn" ] ; then
	    dt=$(df / | grep /dev)
	    dt=${dt:5}
	    dt=${dt%% *}
	    error="(smartctl device_type '$dt' not supported"
	    failed=device 
	fi
	[[ $error ]] && echo "$error"
    else	    
	error="smartmontools missing."
	failed="missing"
	echo "$error. FAIL"
    fi
} > ${tmplog} 2>&1
echo "diskcheck `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

# the index into dirveinv array
name=0; driver=1; type=2; size=3; temp=4; model=5; serial=6;
unset -v driveinv ; declare -a driveinv=()

# put smartctl --scan into driveinv array
# a better control flow control could be used 
case $failed in
    scan )
	echo -n "$error Attempt alternet method) "
	placeholder=" . . . . . device"
	case $os in
	    Linux )
		list="a b c d e f g h i j k l m n o p"
		for i in $list
		do
		    if [ -b /dev/sd${i} ] ; then
			buildscan+="/dev/sd${i} $placeholder"
		    fi
		done
		;;
	    FreeBSD )
		list="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15"
		for i in $list
		do
		    [[ -b /dev/da${i} ]] && buildscan+="/dev/da${i} $placeholder " 
		    [[ -c /dev/ad${i} ]] && buildscan+="/dev/ad${i} $placeholder " 
		done
		;;
	    * )
		echo "Internal error"
		exit
		;;
	esac
	declare -a scan=($buildscan)
	;;
    missing | device )
	echo "$error. FAIL"
	exit
	;;
    * )
        # get the output of --scan into array scan
	unset -v scan ; declare -a scan=($($SMARTCTL --scan))
	;;
esac
    unset -v drive ; declare -a drivescan=()
    #now split up each line using 'device' into the array drivescan
    # This is an example of the string we are parsing:
    # '/dev/sdb -d scsi # /dev/sdb, SCSI device'    
    y=0
     for elm in ${scan[@]} ; do
set +u
	drivescan[$y]="${drivescan[$y]} ${elm}"
	[[ "${elm}" == "device" ]] && ((++y))
set -u
    done

for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${drivescan[$idx]})
    lend=${#d[*]} ; x=$((lend - 2))

    #name
    cnt=${#driveinv[$idx]}
    lname="${d[0]}"
    sname="${lname:5}"
    [[  "$sname" == "pass2" ]] && break # /dev/pass2 on freebsd is tape device, skip
    driveinv[$idx]="$sname"
    #if we did not get any info then fill in value meaning unknown.
    [[ ${#driveinv[*]} -eq $cnt ]] && driveinv[$idx]="MissingCMD"
    driveinv[$idx]+=" "

    #driver
    cnt=${#driveinv[$idx]}
    driveinv[$idx]+="${d[2]}"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "

    #type
    cnt=${#driveinv[$idx]}
    driveinv[$idx]+="${d[$x]}"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "

    #size
    cnt=${#driveinv[$idx]}
    sz="$($SMARTCTL  -i ${d[0]} | grep -i "capacity" | awk '{print $5$6}' | sed s/[][]//g)"
    if [[ $sz ]] ; then
	driveinv[$idx]+="$sz"
	else
	x=$($SMARTCTL  -i ${d[0]} | grep -i "capacity" | awk '{print $3}' | sed s/,//g)
	[[ $x ]] && sz=$(hbis $x) || sz="UKN"
	driveinv[$idx]+="$sz"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "

    #temp
    cnt=${#driveinv[$idx]}
        #type 1
    driveinv[$idx]+="$($SMARTCTL  -l scttempsts ${d[0]} | grep -i "Current Temperature:" | awk '{print $3}')"
    if [ ${#driveinv[idx]} -eq $cnt ] ; then
        #type 2
	driveinv[$idx]+="$($SMARTCTL  -a ${d[0]} | grep -i "Current Drive Temperature:" | awk '{print $4}')"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "

    #vendor product
    cnt=${#driveinv[$idx]}
        #type 1
    driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Device Model:" | awk '{print $3$4}')"
    if [ ${#driveinv[idx]} -eq $cnt ] ; then
        #type 2
	driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Product:" | awk '{print $2}')"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "

    # serial number
    driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Serial Number:" | awk '{print $3}')"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UKN"
    driveinv[$idx]+=" "
done

## # does number of drives and size match ?
## # getfromtb operation node_id drivename drive size
## for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
##     unset -v d ; declare -a d=(${driveinv[$idx]})
##     tbdata=getfromtb $host driveinfo ${d[$name]} 
## done

#output to log file
{
echo -e "name\tdriver\ttype\tsize\ttemp\tmodel\t\tserial"
for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${driveinv[$idx]})
    echo -e "${d[$name]}\t${d[$driver]}\t${d[$type]}\t${d[$size]}\t${d[$temp]}\t${d[$model]}\t${d[$serial]}"
done
} > ${tmplog} 2>&1
cat ${tmplog} >> ${logfile} 

driveinfo=""

for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${driveinv[$idx]})
    echo -n "${d[$name]} ${d[$size]} ${d[$serial]}  "
    driveinfo+="${d[$serial]} "
done
driveinfo=${driveinfo% } # get rid of trailing space

# Now check against the testbed DB

tbinfo=$(getfromtb diskinfo $host)
error=$?
# echo drivesize:$drivesize: tbinfo:$tbinfo: error:$error

[[ "$tbinfo" == "$driveinfo" ]] && failed="" || failed="TBmiss Found |$driveinfo| DBsays |$tbinfo|"


[[ ${failed} ]] && echo " ${failed} FAILED" || echo " OK"

exit 0


