#! /bin/bash

echo -n ' Starting diskcheck..'

# find the number of disks
# find the size of each disk

# first arg is the log output file, if not set then /tmp/...

#Global
declare failed=""
declare error=""
declare err=""

source getfromtb.sh
source hbis.sh
source checkutils.sh

main() {
    inithostname
    initlogs $@

    SMARTCTL=$(findSmartctl)
    drivenames=$(getdrivenames)

    if [ -z "$drivenames" ] ; then
	echo "No drives found. exit"
	exit 1
    fi
    


#XXX XXX     disknames=$(getdriveinfo ${logout} ${tmpout})
#XXX XXX     ## echo disknames:$disknames
#XXX XXX     cat ${tmpout} ; rm -f ${tmpout}
#XXX XXX     echo "diskcheck `date`" >> ${logfile}
#XXX XXX     cat ${logout} >> ${logfile} ; rm -f ${logout}

#echo "" ; echo -n "$0:${LINENO} " ; echo drivenames:${disknames}:

    #turn string into array
#XXX XXX    unset -v scan; declare -a scan=(${drivename// / })

#echo -n "$0:${LINENO} " ; echo scan:"${scan[@]}":

    # the index into dirveinv array
    name=0; driver=1; type=2; size=3; temp=4; 
    model=5; serial=6; bpers=7; sectors=8;

    # array to put drive inventory
    unset -v driveinv ; declare -a driveinv=()
    # array of drives to hold each drive inventory
echo ""
echo "drivenames:||$drivenames||"
    unset -v drive ; declare -a drive=($drivenames)

numberofdrives=${#drive[*]}
echo len=$len
for (( i = 0; i < $len ; i++ )) ; do
    echo drive:$i = ${drive[$i]}
done 
exit	
	
    

#now split up each line using 'device' into the array drivescan
# This is an example of the string we are parsing:
# '/dev/sdb -d scsi # /dev/sdb, SCSI device'    
unset -v drive ; declare -a drivescan=()
y=0
for elm in ${scan[@]} ; do
    set +u
    drivescan[$y]="${drivescan[$y]} ${elm}"
    [[ "${elm}" == "device" ]] && ((++y))
    set -u
done
for ((idx=0; idx<${#drivescan[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${drivescan[$idx]})
    lend=${#d[*]} ; x=$((lend - 2))
    
    #name
    cnt=${#driveinv[$idx]}
    lname="${d[0]}"
    sname="${lname:5}"
    [[  "$sname" == "pass2" ]] && break # /dev/pass2 on freebsd is tape device, skip
    driveinv[$idx]="$sname"
    #if we did not get any info then fillin value meaning unknown.
    [[ ${#driveinv[*]} -eq $cnt ]] && driveinv[$idx]="MissingDRIVE"
    driveinv[$idx]+=" "
    
    #driver
    cnt=${#driveinv[$idx]}
    driveinv[$idx]+="${d[2]}"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
    
    #type
    cnt=${#driveinv[$idx]}
    driveinv[$idx]+="${d[$x]}"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
    
    #size
    cnt=${#driveinv[$idx]}
    sz="$($SMARTCTL  -i ${d[0]} | grep -i "capacity" | awk '{print $5$6}' | sed s/[][]//g)"
    if [[ $sz ]] ; then
	driveinv[$idx]+="$sz"
    else
	x=$($SMARTCTL  -i ${d[0]} | grep -i "capacity" | awk '{print $3}' | sed s/,//g)
	[[ $x ]] && sz=$(hbis $x) || sz="UNK"
	driveinv[$idx]+="$sz"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
    
    #temp
    cnt=${#driveinv[$idx]}
        #type 1
    driveinv[$idx]+="$($SMARTCTL  -l scttempsts ${d[0]} | grep -i "Current Temperature:" | awk '{print $3}')"
    if [ ${#driveinv[idx]} -eq $cnt ] ; then
        #type 2
	driveinv[$idx]+="$($SMARTCTL  -a ${d[0]} | grep -i "Current Drive Temperature:" | awk '{print $4}')"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
    
    #vendor product
    cnt=${#driveinv[$idx]}
        #type 1
    driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Device Model:" | awk '{print $3$4}')"
    if [ ${#driveinv[idx]} -eq $cnt ] ; then
        #type 2
	driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Product:" | awk '{print $2}')"
    fi
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
    
    # serial number
    cnt=${#driveinv[$idx]}
    driveinv[$idx]+="$($SMARTCTL  -i ${d[0]} | grep -i "Serial Number:" | awk '{print $3}')"
    [[ ${#driveinv[idx]} -eq $cnt ]] && driveinv[$idx]+="UNK"
    driveinv[$idx]+=" "
done

## # does number of drives and size match ?
## # getfromtb operation node_id drivename drive size
## for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
##     unset -v d ; declare -a d=(${driveinv[$idx]})
##     tbdata=getfromtb $host driveinfo ${d[$name]} 
## done

#output to log file
{
echo -e "name\tdriver\ttype\tsize\ttemp\tmodel\t\tserial"
for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${driveinv[$idx]})
    echo -e "${d[$name]}\t${d[$driver]}\t${d[$type]}\t${d[$size]}\t${d[$temp]}\t${d[$model]}\t${d[$serial]}"
done
} > ${tmplog} 2>&1
cat ${tmplog} >> ${logfile} 


driveinfo=""

# echo name,size and serial to stdout, addr serialnumber
for ((idx=0; idx<${#driveinv[*]}; idx++)) ; do
    unset -v d ; declare -a d=(${driveinv[$idx]})
    echo -n "${d[$name]} ${d[$size]} ${d[$serial]}  "
    driveinfo+="${d[$serial]} "
done
driveinfo=${driveinfo% } # get rid of trailing space

# Now check against the testbed DB

tbinfo=$(getfromtb diskinfo $host)
error=$?
# echo drivesize:$drivesize: tbinfo:$tbinfo: error:$error


{ 
#save for both output to stdout and log file 
if [ -z "$tbinfo" ] ; then
    failed="TBmiss no info"
    echo "TBmiss empty info returned. Have ${tbinfo[@]} FAILED"
fi

#lower case
tbinfo=${tbinfo,,}
driveinfo=${driveinfo,,}
# turn space seperated string into array
unset -v tb; declare -a tb=(${tbinfo// / })
unset -v have; declare -a have=(${driveinfo// / })

havecnt=${#have[*]}
tbcnt=${#tb[*]}
numserial=${tbcnt}
maxcnt=${tbcnt}

if [[ ${tbcnt} -ne ${havecnt} ]] ; then
    failed="TBmiss"
    [[ ${tbcnt} -gt ${havecnt} ]] && maxcnt=${tbcnt} || maxcnt=${havecnt}
fi

for ((idx=0; idx<$maxcnt; idx++)) ; do
    for ((ifi=0; ifi<$havecnt; ifi++)) ; do
	for ((tbi=0; tbi<$tbcnt; tbi++)) ; do
	    if [ "${have[$ifi]}" = "${tb[$tbi]}" ] ; then
		have[$ifi]=''
		tb[$tbi]=''
	    fi
	done
    done
done
#turn array into string
haveresult=${have[@]}
tbresult=${tb[@]}

if [[ "$haveresult" || "$tbresult" ]] ; then
    if [[ $haveresult ]] ; then
	failed="${failed}: NotIn TB $haveresult"
    fi
    if [[ $tbresult ]] ; then
	failed="${failed}: TB Claims $tbresult"
    fi
fi

echo -n "Have $havecnt drive"
[[ ${havecnt} -gt 1 ]] && echo -n "s" 
[[ -z ${failed} ]] && echo " OK" || echo " $failed" FAILED


} > ${tmplog} 2>&1
cat ${tmplog} >> $logfile
cat ${tmplog}

}

getdriveinfo () {
#need to make sure smartcrl is installed
{
#    echo -n "${FUNCNAME[0]}:${LINENO} " ; echo "args::$@::"
    declare buildscan=""
    logout="$1"
    tmpout="$2"

    if [ "${SMARTCTL}" != "$NOSM" ] ; then
	rtn=$($SMARTCTL --scan)
	# unrecongnized
	if [ -n "$(echo $rtn | grep 'UNRECOGNIZED OPTION')" ] ; then
	    error="(smartctl option '--scan' not supported. Attempt alternet method) "
	    err=scan
	elif [ -n "$(echo $rtn | grep -v 'device')" ] ; then
            # output in unexpected format - missing deliminator "device"
	    error="(smartctl option '--scan' strange ouput. Attempt alternet method) "
	    err=scan
	# empty
	elif [ -z "$rtn" ] ; then
	    dt=$(df / | grep /dev)
	    dt=${dt:5}
	    dt=${dt%% *}
	    error="(smartctl device_type '$dt' not supported"
	    err=device
	fi
	[[ $error ]] && echo "$error"
    else
	error="smartmontools missing."
	err="missing"
	echo "$error. FAIL "
    fi
} > ${logout} 2>&1

# put smartctl --scan into driveinv array
# a better control flow control could be used 

placeholder=" . . . . . device"
case $err in
    scan | missing | device )
	case $os in
	    Linux )
		list="a b c d e f g h i j k l m n o p"
		for i in $list
		do
		    if [ -b /dev/sd${i} ] ; then
			buildscan+="/dev/sd${i} $placeholder"
		    fi
		done
		;;
	    FreeBSD )
		list="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15"
		for i in $list
		do
		    [[ -b /dev/da${i} ]] && buildscan+="/dev/da${i} $placeholder " 
		    [[ -c /dev/ad${i} ]] && buildscan+="/dev/ad${i} $placeholder " 
		    [[ -c /dev/amrd${i} ]] && buildscan+="/dev/amrd${i} $placeholder " 
		done
		;;
	    * )
		echo "${FUNCNAME[0]}:${LINENO} Internal error"
		exit
		;;
	esac
	unset -v scan
	[[ $buildscan ]] && declare -a scan=($buildscan) || declare -a scan=("")
#	echo -n "${FUNCNAME[0]}:${LINENO} " ; echo "buildscan::${buildscan}::"
	;;
    root )
	echo -n "$error. FAIL " >> ${tmpout}
	echo "Last attempt return roots mount point" >> ${tmpout}
	x=$(df / | grep /dev)
	lastattempt="${x%% *} $placeholder "
	unset -v scan ; declare -a scan=($lastattempt)
	;;
    * )
        # get the output of --scan into array scan
	 unset -v scan ; declare -a scan=($rtn)
#	 echo -n "${FUNCNAME[0]}:${LINENO} " ; echo "rtn::${rtn}::"
	;;
esac

# the result
echo -n "${scan[@]}"

}

main $@

exit 0


