#! /bin/bash

# find the read and write speed of the disks on the system

source getfromtb.sh

os=`uname`
host=`hostname`
failed=""
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi

# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

set +x 
#exit on unbound var
set -u


logfile=$1

{

} >> ${tmplog} 2>&1

echo "diskspeedtest `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

[[ -z ${failed} ]] && echo ". . . diskspeedtest OK" || echo ". . . diskspeedtest FAILED"

exit 0


