#! /bin/sh

logfile=$1

host=`hostname`
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi

echo "${host}: memtest `date` OK" >> ${logfile}

echo ". . . memtest OK"
echo -n ""
exit 0
