#! /bin/sh

ntpserver="155.98.32.70"
#ntpserver="time.xmission.com"

os=`uname`
host=`hostname`
failed=""
if [ -e "/var/emulab/boot/realname" ]; then
    host=`cat /var/emulab/boot/realname`
fi


# setup logging
if [ $1 ] ; then
    logfile=$1
else
    logfile="/tmp/nodecheck.log"
fi
tmplog=/tmp/.$$.log
cat /dev/null > ${tmplog}

#set +x
#exit on unbound var
#set -u

{
case $os in
    Linux | FreeBSD )
	unset -v d ; declare -a d=($(ntpdate -q $ntpserver))
	for ((idx=0; idx<${#d[*]}; idx++)) ; do
	    [[ "${d[idx]}" == "offset" ]] && break
	done
	((++idx))
	z=${d[idx]}
	offset=$(echo ${z} | tr -d ,)
	[[ $offset < 0 ]] && a=$(echo "-(10 * $offset)" | bc) || a=$(echo "(10 * $offset)" | bc)
	[[ $a > 1 ]] && failed=FAIL
	[[ $failed ]] && echo "Time check failed offset $offset greater then 1 second " || echo "Time check passed offset $offset"
	;;
    * )
	echo "os $os unknown"
	offset="-1"
	failed=FAIL
	;;
esac
} >> ${tmplog} 2>&1

echo "timecheck `date`" >> ${logfile}
cat ${tmplog} >> ${logfile} 

[[ -z ${failed} ]] && echo ". . . timecheck offset $offset OK" || echo ". . . timecheck offset $offset FAILED"

exit 0
